import turtle as t
import numpy as np

t.shape('turtle')
t.color('black')
t.fillcolor('yellow')
t.begin_fill()
t.circle(100)
t.end_fill()
t.penup()
t.goto(-35, 120)
t.pendown()
t.color('black')
t.fillcolor('white')
t.begin_fill()
t.circle(15)
t.end_fill()
t.penup()
t.goto(35, 120)
t.pendown()
t.color('black')
t.fillcolor('white')
t.begin_fill()
t.circle(15)
t.end_fill()
t.penup()
t.goto(-35, 125)
t.pendown()
t.color('black')
t.fillcolor('black')
t.begin_fill()
t.circle(7)
t.end_fill()
t.penup()
t.goto(35, 125)
t.pendown()
t.color('black')
t.fillcolor('black')
t.begin_fill()
t.circle(7)
t.end_fill()
t.penup()
t.goto(-17, 60)
t.pendown()
t.fillcolor('black')
t.begin_fill()
a = 30
b = 18
dx = t.xcor()
dy = t.ycor()
for deg in range(361):
    rad = np.radians(deg)
    y = a * np.sin(rad) + dy
    x = -b * np.cos(rad) + b + dx
    t.goto(x, y)
t.end_fill()
