import turtle

#1
def first():
    turtle.shape('turtle')
    turtle.forward(5)
    turtle.left(90)
    turtle.forward(5)
    turtle.left(90)
    turtle.forward(5)
    turtle.left(90)
    turtle.forward(5)
    turtle.penup()
    turtle.right(45)
    turtle.forward(3)
    turtle.left(135)
    turtle.pendown()

#2
def second():
    turtle.shape('turtle')
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(10)
    turtle.penup()
    turtle.right(45)
    turtle.forward(3)
    turtle.left(135)
    turtle.pendown()

#3
def third():
    turtle.shape('turtle')
    turtle.forward(15)
    turtle.left(90)
    turtle.forward(15)
    turtle.left(90)
    turtle.forward(15)
    turtle.left(90)
    turtle.forward(15)
    turtle.penup()
    turtle.right(45)
    turtle.forward(3)
    turtle.left(135)
    turtle.pendown()

#4
def fourth():
    turtle.shape('turtle')
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(20)
    turtle.penup()
    turtle.right(45)
    turtle.forward(3)
    turtle.left(135)
    turtle.pendown()

#5
def fifth():
    turtle.shape('turtle')
    turtle.forward(25)
    turtle.left(90)
    turtle.forward(25)
    turtle.left(90)
    turtle.forward(25)
    turtle.left(90)
    turtle.forward(25)
    turtle.penup()
    turtle.right(45)
    turtle.forward(3)
    turtle.left(135)
    turtle.pendown()

#6
def sixth():
    turtle.shape('turtle')
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(30)
    turtle.penup()
    turtle.right(45)
    turtle.forward(3)
    turtle.left(135)
    turtle.pendown()

#7
def seventh():
    turtle.shape('turtle')
    turtle.forward(35)
    turtle.left(90)
    turtle.forward(35)
    turtle.left(90)
    turtle.forward(35)
    turtle.left(90)
    turtle.forward(35)
    turtle.penup()
    turtle.right(45)
    turtle.forward(3)
    turtle.left(135)
    turtle.pendown()

#8
def eighth():
    turtle.shape('turtle')
    turtle.forward(40)
    turtle.left(90)
    turtle.forward(40)
    turtle.left(90)
    turtle.forward(40)
    turtle.left(90)
    turtle.forward(40)
    turtle.penup()
    turtle.right(45)
    turtle.forward(3)
    turtle.left(135)
    turtle.pendown()

#9
def ninth():
    turtle.shape('turtle')
    turtle.forward(45)
    turtle.left(90)
    turtle.forward(45)
    turtle.left(90)
    turtle.forward(45)
    turtle.left(90)
    turtle.forward(45)
    turtle.penup()
    turtle.right(45)
    turtle.forward(3)
    turtle.left(135)
    turtle.pendown()

#10
def tenth():
    turtle.shape('turtle')
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(50)
    turtle.penup()
    turtle.right(45)
    turtle.forward(3)
    turtle.left(135)
    turtle.pendown()

for i in range (1):
    first()
    second()
    third()
    fourth()
    fifth()
    sixth()
    seventh()
    eighth()
    ninth()
    tenth()
